# -*- coding: utf-8 -*-
"""jpegtopng.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VawrHuMDuQ-0DFzv4ZbcU10fJUt3n2uy

# ***CONVERT JPG TO PNG USING PYTHON***
"""

from PIL import Image
from glob import glob
import cv2

"""* Saving png format to current file."""

from glob import glob                                                           
import cv2 
pngs = glob('FilePath/*.jpg')
file ='TargetFilePath/'

for j in pngs:
    img = cv2.imread(j)
    cv2.imwrite(j[:-3] + 'png', img)

"""Convert Jpeg to png at target location"""

import sys
import os
from PIL import Image
input_path_fraktur = 'FilePath/'
output_path_fraktur = 'TargetFilePath/'

for filename in os.listdir(input_path_fraktur):
    current_img = Image.open(input_path_fraktur  + filename)
    print('Working on: ' + os.path.splitext(filename)[0])
    print(
        f'Format: {current_img.format}, Size: {current_img.size}, Mode: {current_img.mode}')

    # coverts the images to PNG + saves to the output folder
    current_img.save( output_path_fraktur + 
                     os.path.splitext(filename)[0] + '.png', 'PNG')

import sys
import os
from PIL import Image
input_path_normal = 'FilePath/'
output_path_normal = 'TargetFilePath/'

for filename in os.listdir(input_path_normal):
    current_img = Image.open(input_path_normal  + filename)
    print('Working on: ' + os.path.splitext(filename)[0])
    print(
        f'Format: {current_img.format}, Size: {current_img.size}, Mode: {current_img.mode}')

    # coverts the images to PNG + saves to the output folder
    current_img.save( output_path_normal + 
                     os.path.splitext(filename)[0] + '.png', 'PNG')